import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";

import { HeaderComponent } from "@/components/header-component";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          className={`${lora.className} flex justify-center p-4 bg-primary text-white h-[100px]`}
        >
          <HeaderComponent />
        </header>
        {children}
      </body>
    </html>
  );
}
