import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";

import { HeaderComponent } from "@/components/header-component";
import { FooterComponent } from "@/components/footer-component";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-background flex flex-col justify-between">
          <header
            className={`${lora.className} flex justify-center items-center p-4 bg-primary text-white h-[150px]`}
          >
            <HeaderComponent />
          </header>
          <main className="flex flex-col items-center bg-foreground h-svh">
            {children}
          </main>
          <footer
            className={`${lora.className} flex justify-center p-4 bg-primary text-white h-[150px]`}
          >
            <FooterComponent />
          </footer>
        </div>
      </body>
    </html>
  );
}
